//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CircuitController
{
	private object _NodeMediator
	{
		get;
		set;
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void CalculateDelay()
	{
		throw new System.NotImplementedException();
	}

}

