//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CircuitBuilder
{
	private object _nodeMap
	{
		get;
		set;
	}

	private object _nodeList
	{
		get;
		set;
	}

	private object _NodeMediator
	{
		get;
		set;
	}

	public virtual IEnumerable<Node> Node
	{
		get;
		set;
	}

	public virtual void Build()
	{
		throw new System.NotImplementedException();
	}

}

