//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NodeMediator
{
	private object _nodes
	{
		get;
		set;
	}

	public virtual void Register()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Send()
	{
		throw new System.NotImplementedException();
	}

}

