//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface Node 
{
	object NextList { get;set; }

	object PreviousList { get;set; }

	object bitList { get;set; }

	void AddNext();

	void AddPrevious();

	void Send();

	void Recieve();

}

