//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NOR : Node
{
	public virtual void AddNext()
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddPrevious()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Send()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Recieve()
	{
		throw new System.NotImplementedException();
	}

}

